### ISSUE TITLE
Error when running app

### ISSUE THREAD

**Issue by here1234** [kboghe/NordVPN-switcher#42]
python 3.9.11

[34mI want to connect to...
_________________________
Type 'help' for available options
[0mamericas

Done!

Traceback (most recent call last):
  File "C:\Good Stuff\nordvpn_switcher-0.2.9\nordvpn_switcher-0.2.9\nordvpn_switcher\test.py", line 6, in <module>
    rotate_VPN(instructions) #refer to the instructions variable here
  File "C:\Program Files\Python39\lib\site-packages\nordvpn_switcher-0.2.9-py3.9.egg\nordvpn_switcher\nordvpn_switch.py", line 457, in rotate_VPN
    current_ip = new_ip = get_ip()
  File "C:\Program Files\Python39\lib\site-packages\nordvpn_switcher-0.2.9-py3.9.egg\nordvpn_switcher\nordvpn_switch.py", line 83, in get_ip
    ip = re.search("IPv4,(.*?),Remaining", ip).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

C:\Good Stuff\nordvpn_switcher-0.2.9\nordvpn_switcher-0.2.9\nordvpn_switcher>

**Comment by SaifMahin22** [comment]
I am also having the same error while trying to initialize_VPN and also rotate vpn.

**Comment by kboghe** [comment]
Hi! Isn't this solved by the solution offered in #40 ? I'll fix this asap and update the pip version soon. :)

**Comment by here1234** [comment]
Just as a heads up this is still an issue I believe.  I tried updating pip and downloading a new master zip.  nothing worked.

**Comment by kboghe** [comment]
> Just as a heads up this is still an issue I believe. I tried updating pip and downloading a new master zip. nothing worked.

I just updated the pip version; could you try again? :) Thanks!

**Comment by here1234** [comment]
It works now.  Thanks.

**Comment by kboghe** [comment]
Awesome; thanks for checking.
